'use client'
import {useState} from 'react'
import {api} from '@/lib/api'

type Product={id:number;name:string;price:number;stock:number}
type Service={id:number;category:string;name:string;variant?:string|null;hairLength?:string|null;price:number;priceIsStartingAt:boolean}
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

export default function ProductsPanel({products,services,onChanged,onLock}:{products:Product[];services:Service[];onChanged:()=>void;onLock:()=>void}){
 const [accessCode,setAccessCode]=useState(''),[authorized,setAuthorized]=useState(false),[accessError,setAccessError]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[confirmOpen,setConfirmOpen]=useState(false),[confirmCode,setConfirmCode]=useState(''),[confirmLabel,setConfirmLabel]=useState(''),[confirmError,setConfirmError]=useState(''),[confirming,setConfirming]=useState(false)
 const [pending,setPending]=useState<((code:string)=>Promise<void>)|null>(null)
 const [name,setName]=useState(''),[price,setPrice]=useState(''),[stock,setStock]=useState(''),[editingProduct,setEditingProduct]=useState<number|null>(null),[editName,setEditName]=useState(''),[editPrice,setEditPrice]=useState(''),[editStock,setEditStock]=useState(''),[editingService,setEditingService]=useState<number|null>(null),[editServicePrice,setEditServicePrice]=useState('')
 const categories=Array.from(new Set(services.map(s=>s.category).filter(Boolean)))
 const [serviceName,setServiceName]=useState(''),[serviceCategory,setServiceCategory]=useState(''),[newServiceCategory,setNewServiceCategory]=useState(''),[serviceVariant,setServiceVariant]=useState(''),[serviceHairLength,setServiceHairLength]=useState(''),[servicePrice,setServicePrice]=useState(''),[servicePriceIsStartingAt,setServicePriceIsStartingAt]=useState(false)
 const headers=(code:string)=>({'X-Admin-Access-Code':accessCode,'X-Admin-Change-Code':code})
 function requestConfirmation(label:string,action:(code:string)=>Promise<void>){setConfirmLabel(label);setPending(()=>action);setConfirmCode('');setConfirmError('');setConfirmOpen(true)}
 function changed(text:string){setMessage(text);setError('');onChanged();window.setTimeout(()=>setMessage(''),4500)}
 async function confirmMutation(e:React.FormEvent){e.preventDefault();if(confirmCode.length!==4)return;setConfirming(true);setConfirmError('');try{if(pending)await pending(confirmCode);setConfirmOpen(false);setPending(null);setConfirmCode('')}catch(e){const message=e instanceof Error?e.message:'';if(message.includes('401')){const attempts=Number(sessionStorage.getItem('adminChangeAttempts')||'0')+1;sessionStorage.setItem('adminChangeAttempts',String(attempts));if(attempts>=3){const until=Date.now()+5*60*1000;localStorage.setItem('adminCadastrosBlockedUntil',String(until));sessionStorage.removeItem('adminChangeAttempts');setConfirmOpen(false);onLock()}else setConfirmError(`Senha incorreta! Alterações não executadas! ${3-attempts} tentativa(s) restante(s).`)}else setConfirmError(message||'Não foi possível concluir a alteração. Tente novamente.')}finally{setConfirming(false)}}
 async function enter(e:React.FormEvent){e.preventDefault();setAccessError('');try{await api('/admin/access',{method:'POST',body:JSON.stringify({accessCode})});setAuthorized(true)}catch{setAccessError('Código de administrador incorreto.');setAccessCode('')}}
 async function createProduct(e:React.FormEvent){e.preventDefault();setError('');requestConfirmation('cadastrar este produto',async code=>{try{await api('/products',{method:'POST',headers:headers(code),body:JSON.stringify({name,price:Number(price),stock:Number(stock)})});setName('');setPrice('');setStock('');sessionStorage.removeItem('adminChangeAttempts');changed('Alteração feita com sucesso! Produto cadastrado.')}catch(e){throw e}})}
 function startProductEdit(p:Product){setEditingProduct(p.id);setEditName(p.name);setEditPrice(String(p.price));setEditStock(String(p.stock));setError('')}
 async function updateProduct(e:React.FormEvent,id:number){e.preventDefault();setError('');requestConfirmation('alterar este produto',async code=>{await api(`/products/${id}`,{method:'PATCH',headers:headers(code),body:JSON.stringify({name:editName,price:Number(editPrice),stock:Number(editStock)})});setEditingProduct(null);sessionStorage.removeItem('adminChangeAttempts');changed('Alteração feita com sucesso! Produto atualizado.')})}
 async function deleteProduct(p:Product){if(!window.confirm(`Excluir o produto ${p.name}?`))return;setError('');requestConfirmation('excluir este produto',async code=>{await api(`/products/${p.id}`,{method:'DELETE',headers:headers(code)});sessionStorage.removeItem('adminChangeAttempts');changed('Alteração feita com sucesso! Produto excluído.')})}
 function startServiceEdit(s:Service){setEditingService(s.id);setEditServicePrice(String(s.price));setError('')}
 async function updateService(e:React.FormEvent,id:number){e.preventDefault();setError('');requestConfirmation('alterar o preço deste serviço',async code=>{await api(`/services/${id}`,{method:'PATCH',headers:headers(code),body:JSON.stringify({price:Number(editServicePrice)})});setEditingService(null);sessionStorage.removeItem('adminChangeAttempts');changed('Alteração feita com sucesso! Serviço e preço atualizados.')})}
 async function createService(e:React.FormEvent){e.preventDefault();setError('');const category=(serviceCategory==='__new__'?newServiceCategory:serviceCategory).trim();if(!category){setError('Informe o tipo ou a categoria do serviço.');return}requestConfirmation('cadastrar este serviço',async code=>{await api('/services',{method:'POST',headers:headers(code),body:JSON.stringify({category,name:serviceName.trim(),variant:serviceVariant.trim()||null,hairLength:serviceHairLength||null,price:Number(servicePrice),priceIsStartingAt:servicePriceIsStartingAt})});setServiceName('');setServiceCategory('');setNewServiceCategory('');setServiceVariant('');setServiceHairLength('');setServicePrice('');setServicePriceIsStartingAt(false);sessionStorage.removeItem('adminChangeAttempts');changed('Alteração feita com sucesso! Serviço cadastrado.')})}
 if(!authorized)return <div className="card mx-auto max-w-md"><h3 className="text-lg font-bold">Acesso do administrador</h3><p className="mt-2 text-sm text-[#756773]">Digite o código de 6 dígitos para acessar os cadastros de produtos e serviços.</p><form onSubmit={enter} className="mt-4 space-y-3"><label><span className="label">Código do administrador</span><input className="field" type="password" inputMode="numeric" autoComplete="off" maxLength={6} pattern="[0-9]{6}" value={accessCode} onChange={e=>setAccessCode(e.target.value.replace(/\D/g,'').slice(0,6))} required/></label>{accessError&&<p role="alert" className="text-sm text-red-700">{accessError}</p>}<button className="btn" disabled={accessCode.length!==6}>Acessar cadastros</button></form></div>
 return <div className="space-y-5">{message&&<div role="status" className="fixed inset-x-4 top-4 z-50 mx-auto max-w-xl rounded-xl border border-green-200 bg-green-50 p-4 text-green-800 shadow-lg">{message}</div>}{error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
 <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={createProduct} className="card"><h3 className="mb-4 font-bold">Cadastrar produto</h3><label className="mb-3 block"><span className="label">Nome</span><input className="field" value={name} onChange={e=>setName(e.target.value)} required/></label><label className="mb-3 block"><span className="label">Preço (R$)</span><input className="field" type="number" min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label className="mb-4 block"><span className="label">Estoque inicial</span><input className="field" type="number" min="0" step="1" value={stock} onChange={e=>setStock(e.target.value)} required/></label><button className="btn">Salvar produto</button></form><div className="card"><h3 className="mb-3 font-bold">Produtos cadastrados</h3>{products.length===0?<p className="text-sm text-[#756773]">Nenhum produto cadastrado.</p>:<div className="space-y-2">{products.map(p=><article key={p.id} className="border-t py-3">{editingProduct===p.id?<form onSubmit={e=>void updateProduct(e,p.id)} className="grid gap-3 sm:grid-cols-3"><label><span className="label">Nome</span><input className="field" value={editName} onChange={e=>setEditName(e.target.value)} required/></label><label><span className="label">Preço</span><input className="field" type="number" min="0.01" step="0.01" value={editPrice} onChange={e=>setEditPrice(e.target.value)} required/></label><label><span className="label">Estoque</span><input className="field" type="number" min="0" step="1" value={editStock} onChange={e=>setEditStock(e.target.value)} required/></label><div className="flex gap-2 sm:col-span-3"><button className="btn">Salvar alterações</button><button type="button" className="rounded-lg border px-4 py-2" onClick={()=>setEditingProduct(null)}>Cancelar</button></div></form>:<div className="flex flex-wrap items-center justify-between gap-3"><div><b>{p.name}</b><div className="text-sm text-[#756773]">Estoque: {p.stock} · {money(p.price)}</div></div><div className="flex gap-2"><button type="button" className="rounded-lg border px-3 py-2" onClick={()=>startProductEdit(p)}>Editar</button><button type="button" className="rounded-lg border border-red-200 px-3 py-2 text-red-700" onClick={()=>void deleteProduct(p)}>Excluir</button></div></div>}</article>)}</div>}</div></section>
 <section className="card"><h3 className="mb-1 font-bold">Catálogo de serviços do agendamento</h3><p className="mb-4 text-sm text-[#756773]">Cadastre novos serviços ou altere os preços. As mudanças serão usadas nos próximos agendamentos; os anteriores mantêm o valor original.</p>
 <form onSubmit={e=>void createService(e)} className="mb-5 rounded-xl border border-[#eadfe8] bg-[#fcf9fb] p-4"><h4 className="mb-3 font-semibold">Cadastrar serviço</h4><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label><span className="label">Nome do serviço</span><input className="field" value={serviceName} onChange={e=>setServiceName(e.target.value)} placeholder="Ex.: Alisamento" required/></label><label><span className="label">Tipo / categoria</span><select className="field" value={serviceCategory} onChange={e=>setServiceCategory(e.target.value)} required><option value="" disabled>Selecione a categoria</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}<option value="__new__">Cadastrar novo tipo…</option></select></label>{serviceCategory==='__new__'&&<label><span className="label">Novo tipo de serviço</span><input className="field" value={newServiceCategory} onChange={e=>setNewServiceCategory(e.target.value)} placeholder="Ex.: Pintura" required/></label>}<label><span className="label">Variação (opcional)</span><input className="field" value={serviceVariant} onChange={e=>setServiceVariant(e.target.value)} placeholder="Ex.: Orgânica"/></label><label><span className="label">Comprimento do cabelo (opcional)</span><select className="field" value={serviceHairLength} onChange={e=>setServiceHairLength(e.target.value)}><option value="">Não se aplica</option><option value="Curto">Curto</option><option value="Médio">Médio</option><option value="Longo">Longo</option><option value="Extra Longo">Extra longo</option></select></label><label><span className="label">Preço (R$)</span><input className="field" type="number" min="0.01" step="0.01" value={servicePrice} onChange={e=>setServicePrice(e.target.value)} required/></label></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={servicePriceIsStartingAt} onChange={e=>setServicePriceIsStartingAt(e.target.checked)}/>Preço a partir de</label><button className="btn mt-4">Salvar serviço</button></form>
 <div className="space-y-2">{services.map(s=><article key={s.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3"><div><b>{s.name}{s.variant&&<> · {s.variant}</>}{s.hairLength&&<> · {s.hairLength}</>}</b><div className="text-sm text-[#756773]">{s.category}{s.priceIsStartingAt?' · a partir de':''}</div></div>{editingService===s.id?<form onSubmit={e=>void updateService(e,s.id)} className="flex items-end gap-2"><label><span className="label">Novo preço (R$)</span><input className="field w-36" type="number" min="0.01" step="0.01" value={editServicePrice} onChange={e=>setEditServicePrice(e.target.value)} required/></label><button className="btn">Confirmar</button><button type="button" className="rounded-lg border px-3 py-2" onClick={()=>setEditingService(null)}>Cancelar</button></form>:<div className="flex items-center gap-3"><b>{money(s.price)}</b><button type="button" className="rounded-lg border px-3 py-2" onClick={()=>startServiceEdit(s)}>Alterar preço</button></div>}</article>)}</div></section>{confirmOpen&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-4"><form onSubmit={e=>void confirmMutation(e)} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h3 className="text-lg font-bold">Confirmar alteração</h3><p className="mt-2 text-sm text-[#756773]">Digite a senha de 4 dígitos para {confirmLabel}.</p><input autoFocus className="field mt-4" type="password" inputMode="numeric" autoComplete="off" maxLength={4} pattern="[0-9]{4}" value={confirmCode} onChange={e=>setConfirmCode(e.target.value.replace(/\D/g,'').slice(0,4))} required/>{confirmError&&<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm font-medium text-red-700">{confirmError}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" className="rounded-lg border px-4 py-2" onClick={()=>setConfirmOpen(false)} disabled={confirming}>Cancelar</button><button className="btn" disabled={confirming||confirmCode.length!==4}>{confirming?'Verificando…':'Confirmar'}</button></div></form></div>}</div>
}
